# Generated by Django 4.0.6 on 2022-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
