# Generated by Django 4.0.3 on 2023-02-17 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
