# Generated by Django 4.0.6 on 2022-08-17 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='freedom land', max_length=225, null=True),
        ),
    ]
