# Generated by Django 4.2.4 on 2024-01-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="user",
        ),
        migrations.CreateModel(
            name="ClimateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField()),
                ("temp", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="src.city"
                    ),
                ),
            ],
        ),
    ]
