# Generated by Django 4.0.6 on 2022-08-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='max',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='min',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
