# Generated by Django 4.0.6 on 2022-08-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_city_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
