# Generated by Django 4.0.6 on 2022-08-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_city_state_city_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
