# Generated by Django 4.0.6 on 2022-08-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_city_name_alter_city_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='freedom land', max_length=225),
        ),
    ]
